apiVersion: apps/v1
kind: Deployment
metadata:
  name: marketdata-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: marketdata-service
  template:
    metadata:
      labels:
        app: marketdata-service
    spec:
      initContainers:
        - name: wait-for-db
          image: postgres:15
          command: ["sh", "-c", "until pg_isready -h marketdata-timescale.default.svc.cluster.local -p 5434 -U marketdata_timescale_user; do echo waiting for db; sleep 3; done"]
      containers:
        - name: marketdata-service
          image: reksaalamsyah/marketdata-service:latest
          ports:
            - containerPort: 8082
          env:
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: marketdata-config
                  key: SPRING_DATASOURCE_USERNAME
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: marketdata-config
                  key: SPRING_DATASOURCE_URL
            - name: MANAGEMENT_ZIPKIN_TRACING_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  key: MANAGEMENT_ZIPKIN_TRACING_ENDPOINT
                  name: common-config
                  
            - name: SPRING_KAFKA_BOOTSTRAP-SERVERS
              valueFrom:
                configMapKeyRef:
                  name: common-config
                  key: SPRING_KAFKA_BOOTSTRAP-SERVERS
            - name: LOKI_URL
              valueFrom:
                configMapKeyRef:
                  name: common-config
                  key: LOKI_URL
            - name: API_GATEWAY_URL
              valueFrom:
                configMapKeyRef:
                  key: API_GATEWAY_URL
                  name: common-config

            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: shared-secrets
                  key: SPRING_DATASOURCE_PASSWORD
            - name: TWELVE_DATA_API_KEY
              valueFrom:
                secretKeyRef:
                  name: shared-secrets
                  key: TWELVE_DATA_API_KEY
            - name: JAVA_TOOL_OPTIONS
              value: "-XX:MaxRAMPercentage=80.0 -XX:InitialRAMPercentage=40.0 -XX:+UseSerialGC -XX:ReservedCodeCacheSize=96M"
            - name: BPL_JVM_THREAD_COUNT
              value: "20"
            - name: BPL_JVM_HEAD_ROOM
              value: "0"
          # resources:
          #   requests:
          #     memory: "256Mi"
          #     cpu: "50m"
          #   limits:
          #     memory: "384Mi"
          #     cpu: "100m"
---
apiVersion: v1
kind: Service
metadata:
  name: marketdata-service
spec:
  selector:
    app: marketdata-service
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: marketdata-config
data:
  SPRING_DATASOURCE_USERNAME: marketdata_timescale_user
  SPRING_DATASOURCE_URL: jdbc:postgresql://marketdata-timescale.default.svc.cluster.local:5434/marketdata_timescale_db
