apiVersion: apps/v1
kind: Deployment
metadata:
  name: topup-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: topup-service
  template:
    metadata:
      labels:
        app: topup-service
    spec:
      containers:
        - name: topup-service
          image: reksaalamsyah/topup-service:latest
          ports:
            - containerPort: 8084
          env:
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: topup-config
                  key: SPRING_DATASOURCE_USERNAME
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: topup-config
                  key: SPRING_DATASOURCE_URL

            - name: SPRING_REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  key: SPRING_REDIS_HOST
                  name: topup-config
            - name: SPRING_REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  key: SPRING_REDIS_PORT
                  name: topup-config

            - name: SPRING_KAFKA_BOOTSTRAP-SERVERS
              valueFrom:
                configMapKeyRef:
                  name: common-config
                  key: SPRING_KAFKA_BOOTSTRAP-SERVERS
            - name: LOKI_URL
              valueFrom:
                configMapKeyRef:
                  name: common-config
                  key: LOKI_URL
            - name: API_GATEWAY_URL
              valueFrom:
                configMapKeyRef:
                  key: API_GATEWAY_URL
                  name: common-config

            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: shared-secrets
                  key: SPRING_DATASOURCE_PASSWORD
            - name: MANAGEMENT_ZIPKIN_TRACING_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  key: MANAGEMENT_ZIPKIN_TRACING_ENDPOINT
                  name: common-config
                  
            - name: JAVA_TOOL_OPTIONS
              value: "-XX:MaxRAMPercentage=80.0 -XX:InitialRAMPercentage=40.0 -XX:+UseSerialGC -XX:ReservedCodeCacheSize=96M"
            - name: BPL_JVM_THREAD_COUNT
              value: "20"
            - name: BPL_JVM_HEAD_ROOM
              value: "0"

          # resources:
          #   requests:
          #     memory: "300Mi"
          #     cpu: "25m"
          #   limits:
          #     memory: "400Mi"
          #     cpu: "100m"
---
apiVersion: v1
kind: Service
metadata:
  name: topup-service
spec:
  selector:
    app: topup-service
  ports:
    - protocol: TCP
      port: 8084
      targetPort: 8084
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: topup-config
data:
  SPRING_DATASOURCE_USERNAME: topup_postgres_user
  SPRING_DATASOURCE_URL: jdbc:postgresql://topup-postgres.default.svc.cluster.local:5438/topup_postgres_db
  SPRING_REDIS_HOST: topup-redis.default.svc.cluster.local
  SPRING_REDIS_PORT: "6381"
